# Generated by Django 3.2.5 on 2021-07-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Телефон')),
                ('f_i_o', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateTimeField(verbose_name='Дата рождения')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('feedback', models.CharField(max_length=255, verbose_name='Отзыв')),
                ('place_of_employment', models.CharField(max_length=255, verbose_name='Место работы')),
                ('salary', models.IntegerField(default=0)),
                ('job_position', models.CharField(max_length=255, verbose_name='Должность')),
                ('technology', models.ManyToManyField(to='candidates.Technology')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'ordering': ['f_i_o'],
            },
        ),
    ]
