# Generated by Django 3.2.5 on 2021-07-06 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20210706_0241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CanditateTechnologies',
            new_name='CandidateTechnology',
        ),
        migrations.AlterModelOptions(
            name='candidatetechnology',
            options={'verbose_name': 'Кандидат-технология', 'verbose_name_plural': 'Кандидаты-технологии'},
        ),
    ]
