# Generated by Django 3.2.5 on 2021-07-06 02:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20210706_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='technologies',
            field=models.ManyToManyField(related_name='list_technologies', through='candidates.CandidateTechnology', to='candidates.Technology'),
        ),
        migrations.AlterField(
            model_name='candidatetechnology',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate', verbose_name='Кандидат'),
        ),
        migrations.AlterField(
            model_name='candidatetechnology',
            name='knowledge_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень знания'),
        ),
        migrations.AlterField(
            model_name='candidatetechnology',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.technology', verbose_name='Технология'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatetechnology',
            unique_together={('candidate', 'technology')},
        ),
    ]
