# Generated by Django 3.2.5 on 2021-07-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_auto_20210706_0547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatetechnology',
            options={'ordering': ['id'], 'verbose_name': 'Кандидат-технология', 'verbose_name_plural': 'Кандидаты-технологии'},
        ),
    ]
